BookingApp/Controllers/DomesticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingApp.Controllers
{
    public class DomesticController : Controller
    {
        // GET: Luzon
        public ActionResult LuzonDestination()
        {
            return View();
        }

        public ActionResult DomesticBooking()
        {
            return View();
        }

        public ActionResult DomesticBooking1()
        {
            return View();
        }
    }
}

BookingApp/Controllers/HomeController.cs
using BookingApp.Models;
using Dapper;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static DataLibrary.Queries.Query;
using PagedList;

namespace BookingApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var caption = GetCaptions();
            List<Captions> captions = new List<Captions>();
            foreach (var item in caption)
            {
                captions.Add(new Captions
                {
                    fh_cap = item.fh_cap,
                    fb_cap = item.fb_cap,
                    sh_cap = item.sh_cap,
                    sb_cap = item.sb_cap,
                    index_title = item.index_title
                });
            }

            ViewBag.Captions = captions;

            var iss = GetIndexSlides();
            List<IndexSlides> indexSlides = new List<IndexSlides>();
            foreach (var slide in iss)
            {
                indexSlides.Add(new IndexSlides
                {
                    is_id = slide.is_id,
                    is_img = slide.is_img
                });
            }
            ViewBag.IndesSS = indexSlides;
            ViewBag.Domestic = indexSlides.Take(1);
            ViewBag.International = indexSlides.Skip(1).Take(1);
            ViewBag.Education = indexSlides.Skip(2).Take(1);

            var fetchIndexContent = GetIdANDImg().Take(12);
            int counts = Convert.ToInt32(Math.Ceiling((double)GetIdANDImg().Count() /12)); 
            List<IndexModel> indexContent = new List<IndexModel>();
            foreach (var row in fetchIndexContent)
            {
                indexContent.Add(new IndexModel
                {
                    p_id = row.p_id,
                    c_id = row.c_id,
                    img = row.img
                });
            }
            ViewBag.IndexItems = indexContent;
            ViewBag.IndexCounts = counts;
            return View();
        }

        public ActionResult GetIndexPage(int NumberofData)
        {
            if (NumberofData == 0)
            {
                var fetchIndexContent = GetIdANDImg().Take(12);
                int counts = Convert.ToInt32(Math.Ceiling((double)GetIdANDImg().Count() / 12));
                List<IndexModel> indexContent = new List<IndexModel>();
                foreach (var row in fetchIndexContent)
                {
                    indexContent.Add(new IndexModel
                    {
                        p_id = row.p_id,
                        c_id = row.c_id,
                        img = row.img
                    });
                }
                var response = new { data = indexContent, c = counts };
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var packages = GetIdANDImg().Where(x => x.c_id == NumberofData).Take(12).ToList();
                int counts = Convert.ToInt32(Math.Ceiling((double)GetIdANDImg().Where(x => x.c_id == NumberofData).Count() / 12));
                List<IndexModel> indexContent = new List<IndexModel>();
                foreach (var row in packages)
                {

                    indexContent.Add(new IndexModel
                    {
                        p_id = row.p_id,
                        c_id = row.c_id,
                        img = row.img
                    });

                }
                var response = new { data = indexContent, c = counts };
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ViewMoreIndex(int rowsCount, int view)
        {
            var packages = GetIdANDImg().OrderByDescending(x => x.p_id).Skip(rowsCount * (view - 1)).Take(rowsCount).ToList();
            List<IndexModel> indexContent = new List<IndexModel>();
            foreach (var row in packages)
            {
                indexContent.Add(new IndexModel
                {
                    p_id = row.p_id,
                    c_id = row.c_id,
                    img = row.img
                });
            }
            return Json(indexContent, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewMoreIndexViaC(int rowsCount, int view, int filter)
        {
            if (filter == 0)
            {
                var packages = GetIdANDImg().OrderByDescending(x => x.p_id).Skip(rowsCount * (view - 1)).Take(rowsCount).ToList();
                List<IndexModel> indexContent = new List<IndexModel>();
                foreach (var row in packages)
                {
                    indexContent.Add(new IndexModel
                    {
                        p_id = row.p_id,
                        c_id = row.c_id,
                        img = row.img
                    });
                }
                return Json(indexContent, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var packages = GetIdANDImg().Where(x => x.c_id == filter).OrderByDescending(x => x.p_id).Skip(rowsCount * (view - 1)).Take(rowsCount).ToList();
                List<IndexModel> indexContent = new List<IndexModel>();
                foreach (var row in packages)
                {
                    indexContent.Add(new IndexModel
                    {
                        p_id = row.p_id,
                        c_id = row.c_id,
                        img = row.img
                    });
                }
                return Json(indexContent, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Booking01()
        {
            return View();
        }

        public ActionResult Booking02()
        {
            return View();
        }

        public ActionResult Booking03()
        {
            return View();
        }

        public ActionResult Booking()
        {
            return View();
        }

        public ActionResult Booking1()
        {
            return View();
        }

        public ActionResult Booking2()
        {
            return View();
        }

        public JsonResult AutoComplete(string str)
        {
          
            string[] places = new string[] {
                "Tokyo",
                "Delhi",
                "Shanghai",
                "Sao Paulo",
                "Mexico City",
                "Cairo",
                "Dhaka",
                "Mumbai",
                "Beijing",
                "Osaka",
                "Karachi",
                "Chongqing",
                "Buenos Aires",
                "Istanbul",
                "Kolkata",
                "Lagos",
                "Manila",
                "Tianjin",
                "Rio De Janeiro",
                "Guangzhou",
                "Moscow",
                "Lahore",
                "Shenzhen",
                "Bangalore",
                "Paris",
                "Bogota",
                "Chennai",
                "Jakarta",
                "Lima",
                "Bangkok",
                "Seoul",
                "Hyderabad",
                "London",
                "Tehran",
                "Chengdu",
                "New York",
                "Wuhan",
                "Ahmedabad",
                "Kuala Lumpur",
                "Riyadh",
                "Surat",
                "Santiago",
                "Madrid",
                "Pune",
                "Dar Es Salaam",
                "Toronto",
                "Johannesburg",
                "Barcelona",
                "St Petersburg",
                "Yangon",
                "Alexandria",
                "Guadalajara",
                "Ankara",
                "Melbourne",
                "Sydney",
                "Brasilia",
                "Nairobi",
                "Cape Town",
                "Rome",
                "Montreal",
                "Tel Aviv",
                "Los Angeles",
                "Medellin",
                "Jaipur",
                "Casablanca",
                "Lucknow",
                "Berlin",
                "Busan",
                "Athens",
                "Milan",
                "Kanpur",
                "Abuja",
                "Lisbon",
                "Surabaya",
                "Dubai",
                "Cali",
                "Manchester",
                "Chicago",
                "Vancouver",
                "Accra",
                "Pretoria",
                "Beirut",
                "Brisbane",
                "Houston",
                "Bhopal",
                "Havana",
                "Tijuana",
                "Hiroshima",
                "Brussels",
                "Perth",
                "Phnom Penh",
                "Mecca",
                "Vienna",
                "Aleppo",
                "Panama City",
                "Bucharest",
                "Hamburg",
                "Warsaw",
                "Budapest",
                "Phoenix",
                "Lyon",
                "Glasgow",
                "Sharjah",
                "Stockholm",
                "Marseille",
                "Auckland",
                "Philadelphia",
                "San Antonio",
                "Munich",
                "Calgary",
                "San Diego",
                "Abu Dhabi",
                "Edmonton",
                "Belgrade",
                "Zurich",

BookingApp/Controllers/InternationalController.cs
using BookingApp.Models;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
//using System.Data.SqlClient;
using MySql.Data.MySqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static DataLibrary.Queries.Query;

namespace BookingApp.Controllers
{
    public class InternationalController : Controller
    { 
        // GET: International
        public ActionResult InternationalDestination()
        {
            return View();
        }

        public ActionResult InternationalDestination1()
        {
            return View();
        }

        public ActionResult InternationalDestination2()
        {
            return View();
        }

        public ActionResult InternationalDestination3()
        {
            return View();
        }

        public ActionResult InternationalDestination4()
        {
            return View();
        }

        public ActionResult InternationalDestination5()
        {
            return View();
        }

        public ActionResult InternationalBooking()
        {
            return View();
        }

        public ActionResult InternationalBooking1()
        {
            return View();
        }

        public ActionResult Sorak()
        {
            return View();
        }

        public ActionResult Brazil()
        {
            return View();
        }

        public ActionResult Xmastokyo()
        {
            return View();
        }

        public ActionResult Bhutan()
        {
            return View();
        }

        public ActionResult Hanoi()
        {
            return View();
        }

        public ActionResult Slovenia()
        {
            return View();
        }

        public ActionResult GoldenTriangle()
        {
            return View();
        }

        public ActionResult Cairo()
        {
            return View();
        }

        [HttpGet]
        public ActionResult TourPackageD(int id)
        {
            var pd = GetPDisplay().OrderByDescending(x => x.p_id).Take(30);
            List<InternationalDisplay> package = new List<InternationalDisplay>();
            foreach (var item in pd)
            {
                package.Add(new InternationalDisplay
                {
                    p_id = item.p_id,
                    p_name = item.p_name,
                    p_price = item.p_price,
                    c_type = item.c_type,
                    bedtype = item.bedtype,
                    currency = item.currency,
                    img = item.img
                });
            }
            ViewBag.PD = package;

            using (IDbConnection con = new MySqlConnection(DataLibrary.Connection.Connect.GetConnectionString()))
            {
                   var result = con.QueryMultiple(@"select gtp.p_id, gtp.p_name, gtp.p_price,
                          gca.c_type, gbr.bedtype, gtp.currency from t_package as gtp, category as gca,
                          bedrooms as gbr where gtp.c_id = gca.c_id and gtp.bedroom = gbr.bed_id
                          and gtp.p_id = @id and gtp.status = 1;
                          select gtd.tdates_id, gtd.dfrom, gtd.dto from traveldates as gtd
                          where gtd.p_id = @id;
                          select ginc.in_id, ginc.name from inclusion as ginc 
                          where ginc.p_id = @id;
                          select con.con_id, con.name from tcondition as con
                          where con.p_id = @id;
                          select exc.ex_id, exc.name from exclusion as exc 
                          where exc.p_id = @id;
                          select fli.fl_id, fli.name from flightdetails as fli
                          where fli.p_id = @id;
                          select iti.it_id, iti.name, iti.description, iti.bmeal, iti.lmeal, iti.dmeal from itinerary as iti
                          where iti.p_id = @id;
                          select img.img_id, img.slides from imagetable as img
                          where img.p_id = @id order by img.img_id limit 1,5;
                          select vi.visa_id, vi.name from visareq as vi
                          where vi.p_id = @id;
                          select img.img_id, img.slides from imagetable as img
                          where img.p_id = @id  
						  order by img.img_id ASC limit 0,1;
                          select ph.ph_id, ph.ph_loc, ph.ph_phtel from photel as ph 
                          where ph.p_id = @id;",
                          new { @id = id});
                var gTp = result.ReadSingle<GuestTP>();
                gTp.guestTDs = result.Read<GuestTD>().ToList();
                gTp.guestINCs = result.Read<GuestINC>().ToList();
                gTp.guestCONs = result.Read<GuestCON>().ToList();
                gTp.guestEXCs = result.Read<GuestEXC>().ToList();
                gTp.guestFLIs = result.Read<GuestFLI>().ToList();
                gTp.guestITIs = result.Read<GuestITI>().ToList();
                gTp.guestIMGs = result.Read<GuestIMG>().ToList();
                gTp.guestVIs = result.Read<GuestVI>().ToList();
                gTp.headerIMG = result.ReadSingleOrDefault<HeaderIMG>();
                gTp.photels = result.Read<Photel>().ToList();
                return View(gTp);
            }
        }

         public ActionResult BookingTP()
         {
            return View();
         }
    }
}

BookingApp/Views/Home/EduTour.cshtml
@*@model PagedList.IPagedList<BookingApp.Models.InternationalDisplay>
    @using PagedList.Mvc;*@
<header>
    <div id="mydemo" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#mydemo" data-slide-to="0" class="active"></li>
            <li data-target="#mydemo" data-slide-to="1"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner my-inner-carousel">
            <div class="carousel-item active">
                <img src="~/Bg-img/tour-package/bhutan/bhutan.jpg" class="img-fluid">
                @*<img  src="~/Bg-img/tour-package/tokyo/christmas-in-tokyo.jpg" class="img-fluid" />*@
                @*<div class="carousel-caption my-captions">
                        <h3>Say something</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>*@
            </div>
            <div class="carousel-item">
                <img src="~/Bg-img/tour-package/brazil/tropical brazil.jpg" class="img-fluid">
                @*<div class="carousel-caption my-captions">
                        <h3>Say something</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>*@
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#mydemo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#mydemo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</header>

<div class="container-fluid text-center bg-white mt-1" id="idivpage">
    <div class="shadow-effect user-div01 mb-2 mt-0 pb-2 large-padding">
        <h2 class="my-font-25 bg-white mb-0 font-red p-md-4 p-sm-3 p-2 p-lg-4 p-xl-4 text-uppercase text-center" style="border-radius:5px 5px 0 0">Educational</h2>
        <p class="font-orange my-font-16 mb-5 pb-3">List of our Educational tour packages</p>
        <div class="row mt-3">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text btn-default">Show</span>
                    </div>
                    <select class="pagesize" onchange="EDisplay()" id="Edrpdwn">
                        <option selected="selected" value="12">12</option>
                        <option value="24">24</option>
                        <option value="36">36</option>
                        <option value="48">48</option>
                        <option value="60">60</option>
                    </select>
                    <div class="input-group-append">
                        <span class="input-group-text btn-default">entries</span>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Search:</span>
                    </div>
                    <input type="text" id="ESearch" class="form-control" />
                </div>
            </div>
        </div>
        <hr class="my-border mt-1 mb-sm-1 mb-1 mb-lg-2 mb-xl-2 mb-md-2" />
        <div class="p-2">
            <div class="row p-xl-5 p-lg-5 p-md-5 p-sm-2" id="pageECallback">

                @foreach (var item in ViewBag.EDp)
                {
                    <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <div class="card my-card">
                            <div class="my-header-card">
                                <a href="@Url.Action("TourPackageD", "International",new { @id = item.p_id})">
                                    <img src="~/DynamicFiles/@item.img" class="hover-animate-img hover-animate-img-2 card card-class" />
                                </a>
                            </div>
                            <div class="my-card-body card">
                                <div class="my-card-caption">
                                    <h3 class="my-font-18">@item.p_name</h3>
                                    <p class="p-0 m-0 my-font-16">
                                        Price:  @string.Format("{0:C}", Convert.ToDecimal(@item.p_price))
                                    </p>
                                    <p class="p-0 m-0 my-font-16">
                                        Bedroom: @item.bedtype
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <input type="hidden" value="@ViewBag.ECounts" id="ecounts" />
            <div class="epages">

            </div>
        </div>
    </div>
</div>


BookingApp/Views/Home/International.cshtml
@using System.Globalization;
<div class="index-class card pb-2">
    <header class="masthead" id="headmaster">
        <div id="demo" class="carousel slide" data-ride="carousel">

            <div class="carousel-inner">
                @foreach (var r in ViewBag.IndesSS)
                {
                    <div class="carousel-item item active">
                        <img src="~/DynamicFiles/@r.is_img" class="img-min-h img-fluid">
                    </div>
                }
            </div>
        </div>
    </header>


    <div class="container-fluid text-center bg-white mt-1" id="idivpage">
        <div class="shadow-effect user-div01 mb-2 mt-0 pb-2 large-padding">
            <h2 class="my-font-25 bg-white mb-0 font-red p-md-4 p-sm-3 p-2 p-lg-4 p-xl-4 text-uppercase text-center" style="border-radius:5px 5px 0 0">International</h2>
            <p class="font-orange my-font-16 mb-5 pb-3">List of our International tour packages</p>
            <div class="row mt-3">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text btn-default">Show</span>
                        </div>
                        <select class="pagesize" onchange="Display()" id="drpdwn">
                            <option selected="selected" value="12">12</option>
                            <option value="24">24</option>
                            <option value="36">36</option>
                            <option value="48">48</option>
                            <option value="60">60</option>
                        </select>
                        <div class="input-group-append">
                            <span class="input-group-text btn-default">entries</span>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Search:</span>
                        </div>
                        <input type="text" id="Search" placeholder="package name, price, bedroom type" class="form-control" />
                    </div>
                </div>
            </div>
            <hr class="my-border mt-1 mb-sm-1 mb-1 mb-lg-2 mb-xl-2 mb-md-2" />
            <div class="p-2">
                <div class="row p-xl-5 p-lg-5 p-md-5 p-sm-2 text-center" id="pageCallback">

                    @foreach (var item in ViewBag.IDp)
                    {
                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 text-center">
                            <div class="card my-card">
                                <div class="my-header-card">
                                    <a href="@Url.Action("TourPackageD", "International",new { @id = item.p_id})">
                                        <img src="~/DynamicFiles/@item.img" class="hover-animate-img hover-animate-img-2 card card-class" />
                                    </a>
                                </div>
                                <div class="my-card-body card">
                                    <div class="my-card-caption">
                                        <h3 class="my-font-18">@item.p_name</h3>
                                        @if (item.currency == "peso")
                                        {
                                            <p class="p-0 m-0 my-font-16">
                                                Price: @string.Format(CultureInfo.GetCultureInfo("en-PH"),
                                         "{0:c}", Convert.ToDecimal(item.p_price))
                                            </p>
                                        }
                                        else
                                        {
                                            <p class="p-0 m-0 my-font-16">
                                                Price: @string.Format("{0:C}", Convert.ToDecimal(item.p_price))
                                            </p>
                                        }
                                        <p class="p-0 m-0 my-font-16">
                                            Bedroom: @item.bedtype
                                        </p>
                                        <fieldset class="scheduler-border">
                                            <legend class="scheduler-border text-dark"><i style='font-size:16px;color:#ff6a00' class="fas fa-calendar-alt"></i> Travel Dates</legend>
                                            <ul class="pt-0 pb-0">
                                                @for (int d = 0; d < item._Dates.Count; d++)
                                                {
                                                    <li class="my-font-13">@item._Dates[d].otDates</li>
                                                }
                                            </ul>
                                        </fieldset>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <input type="hidden" value="@ViewBag.Counts" id="counts" />
                <div class="pages">

                </div>
            </div>
        </div>
    </div>
</div>



BookingApp/Views/Home/Passenger01.cshtml

@model BookingApp.Models.Passengers


<div class="uw">
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger my-font-14" })
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                <div class="form-group">
                    @Html.LabelFor(x => x.Adults, htmlAttributes: new { @class = "control-label font-red my-font-14" })
                    <div class="input-group">
                        @Html.EditorFor(x => x.Adults, new { htmlAttributes = new { @class = "form-control my-font-14", @placeholder = "Adult count(s)", @id = "-Adult", @pattern = "[0-9]*" } })
                        <div class="input-group-append">
                            <div class="input-group-text my-icon my-font-14"><i class="fas fa-male"></i></div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Adults, "", new { @class = "text-danger my-font-14", @id = "-Errmsg01" })
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                @Html.LabelFor(x => x.Child, htmlAttributes: new { @class = "control-label font-red my-font-14" })
                <div class="input-group">
                    @Html.EditorFor(x => x.Child, new { htmlAttributes = new { @class = "form-control my-font-14", @id = "-Child", @placeholder = "Child count(s)" } })
                    <div class="input-group-append">
                        <div class="input-group-text my-icon my-font-14"><i class="fas fa-child"></i></div>
                    </div>
                </div>
                @Html.ValidationMessageFor(x => x.Child, "", new { @class = "text-danger my-font-14", @id = "-Errmsg02" })
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                @Html.LabelFor(x => x.Infant, htmlAttributes: new { @class = "control-label font-red my-font-14" })
                <div class="input-group">
                    @Html.EditorFor(x => x.Infant, new { htmlAttributes = new { @class = "form-control my-font-14", @id = "-Infant", @placeholder = "Infant count(s)", @min = "0", @max = "10" } })
                    <div class="input-group-append">
                        <div class="input-group-text my-icon my-font-14"><i class="fa fa-baby"></i></div>
                    </div>
                </div>
                @Html.ValidationMessageFor(x => x.Infant, "", new { @class = "text-danger my-font-14", @id = "-Errmsg03" })
            </div>
        }
    </div>
</div>

BookingApp/Views/Home/_International.cshtml
@model PagedList.IPagedList<BookingApp.Models.InternationalDisplay>
@foreach (var item in Model)
{
    <div class="col-12 col-sm-2 col-md-3 col-lg-3 col-xl-3">
        <div class="p-3 text-left">
            <div class="shadow-effect-2" style="border-radius: 5px">
                <a href="@Url.Action("TourPackageD", "International",new { @id = item.p_id})">
                    <img src="~/DynamicFiles/@item.img" class="hover-animate-img m-0 img-fluid hover-animate-img-2 card card-class" /></a>
                    <div class="p-2 card">
                        <p class="m-0 p-0 font-red">
                            Package Name: <strong class="font-orange">@item.p_name</strong>
                        </p>
                        <p class="m-0 p-0 font-red">
                            Price: <strong class="font-orange">  @string.Format("{0:C}", Convert.ToDecimal(@item.p_price))</strong>
                        </p>
                        <p class="m-0 p-0 font-red">
                            Bedroom: <strong class="font-orange">@item.bedtype</strong>
                        </p>
                    </div>
            </div>
        </div>
    </div>
}