BookingApp/Areas/AdminPanel/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Data;
//using System.Data.SqlClient;
using MySql.Data.MySqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BookingApp.Areas.AdminPanel.Models;
using Dapper;
using DataLibrary.Security;
using Newtonsoft.Json;
using static DataLibrary.Queries.Query;

namespace BookingApp.Areas.AdminPanel.Controllers
{
    [SecurityAuthenticate(Roles = "SuperAdmin")]
    public class ControlPanelController : Controller
    {
        public ActionResult Index()
        {
            var _otds = GetOTDates();
            List<Dates> dates = new List<Dates>();
            foreach (var row in _otds)
            {
                dates.Add(new Dates
                {
                    p_id = row.p_id,
                    tdates_id = row.tdates_id,
                    dfrom = row.dfrom,
                    dto = row.dto
                });
            }

            var otDs = GetOTDids();
            List<OutToDateP> oTDP = new List<OutToDateP>();
            foreach (var row in otDs)
            {
                oTDP.Add(new OutToDateP
                {
                    p_id = row.p_id,
                    p_name = row.p_name,
                    p_img = row.img
                });
            }

            var listGroup = oTDP.GroupJoin(dates,
                            otdp => otdp.p_id,
                            d => d.p_id,
                            (otdp, _dates) => new OTDPView
                            {
                                p_id = otdp.p_id,
                                p_name = otdp.p_name,
                                p_img = otdp.p_img,
                                _Dates = _dates.ToList()
                            });
            ViewBag.OTDList = listGroup;
            return View();
        }

        public ActionResult Slides()
        {
            return View();
        }

        public ActionResult GetIss()
        {
            var iss = GetIndexSlides();
            List<IndexSlide> iSs = new List<IndexSlide>();
            foreach (var item in iss)
            {
                iSs.Add(new IndexSlide
                {
                    is_id = item.is_id,
                    is_img = item.is_img
                });
            }

            return Json(iSs, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCaption()
        {
            var caption = GetCaptions();
            List<Captions> captions = new List<Captions>();
            foreach(var item in caption)
            {
                captions.Add(new Captions
                {
                    cap_id = item.cap_id,
                    fh_cap = item.fh_cap,
                    fb_cap = item.fb_cap,
                    sh_cap = item.sh_cap,
                    sb_cap = item.sb_cap,
                    index_title = item.index_title
                });
            }
            return Json(captions, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditCaption(int id)
        {
            var caption = GetCaptions().Where(x => x.cap_id == id);
            List<Captions> captions = new List<Captions>();
            foreach (var item in caption)
            {
                captions.Add(new Captions
                {
                    cap_id = item.cap_id,
                    fh_cap = item.fh_cap,
                    fb_cap = item.fb_cap,
                    sh_cap = item.sh_cap,
                    sb_cap = item.sb_cap,
                    index_title = item.index_title
                });
            }
            return Json(captions, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateIndexT(string uindexT)
        {
            try
            {
                int uIndexT = UIndexT(uindexT);
                return Json("Index title successfuly updated, " +uIndexT + " row(s) affected!");
            }
            catch(Exception ex)
            {
                return Json("Error: "+ ex.Message);
            }
        }

        public ActionResult UpdateFCs(string uFC)
        {
            try
            {
                int uFc = UpdateFC(uFC);
                return Json("Index slide first caption successfuly updated, "+ uFc+" row(s) affected!");
            }
            catch (Exception ex)
            {
                return Json("Error: "+ex.Message);
            }
        }

        public ActionResult UpdateSCs(string USC)
        {
            try
            {
                int uSC = UpdateSC(USC);
                return Json("Index second caption successfuly updated, "+uSC+" row(s) affected!");
            }
            catch (Exception ex)
            {
                return Json("Error: "+ex.Message);
            }
        }

        public ActionResult RetrieveIss(int id)
        {
            var iss = GetIndexSlides().Where(x => x.is_id == id);
            List<IndexSlide> iSs = new List<IndexSlide>();
            foreach (var item in iss)
            {
                iSs.Add(new IndexSlide
                {
                    is_id = item.is_id,
                    is_img = item.is_img
                });
            }

            return Json(iSs, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateIss(int id, HttpPostedFileBase file)
        {
            try
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/DynamicFiles/"), fileName);
                int uImage = UIssSlides(id, file.FileName);
                file.SaveAs(path);
                return Json("Index slide successfuly updated, " + uImage + " row(s) affected!");
            }
            catch (Exception ex)
            {
                return Json("Error: " + ex.Message);
            }
        }

        public ActionResult DeleteIss(int id)
        {
            try
            {
                var selImg = GetIndexSlides().Where(x => x.is_id == id);
                List<IndexSlide> iSs = new List<IndexSlide>();
                foreach (var item in selImg)
                {
                    iSs.Add(new IndexSlide
                    {
                        is_id = item.is_id,
                        is_img = item.is_img
                    });
                }
                if (iSs[0].is_img != null)
                {
                    string fullpath = Request.MapPath("~/DynamicFiles/" + iSs[0].is_img);
                    if (System.IO.File.Exists(fullpath))
                    {
                        System.IO.File.Delete(fullpath);
                    }

                }
                int Delimg = DeleteISS(id);
                return Json("Index slide successfuly deleted, " + Delimg + " row(s) affected!");
            }
            catch (Exception ex)
            {
                return Json("Error: " + ex.Message);
            }
        }

        public ActionResult UploadSlide()   
        {
            string path = Server.MapPath("~/DynamicFiles/");
            HttpFileCollectionBase files = Request.Files;
            for (int i = 0; i < files.Count; i++)
            {
                HttpPostedFileBase file = files[i];
                file.SaveAs(path + file.FileName);
                int insertSlide = AddIndexSlide(file.FileName);
            }
            return Json(files.Count + " Files Uploaded");
        }

        public ActionResult GetPList()
        {
            var pList = Packagelist();
            List<PackageList> packagelists = new List<PackageList>();
            foreach (var row in pList)
            {
                packagelists.Add(new PackageList
                {
                    p_id = row.p_id,
                    p_name = row.p_name,
                    p_price = row.p_price,
                    c_id = row.c_id,
                    c_type = row.c_type,
                    bed_id = row.bed_id,
                    bedtype = row.bedtype,
                    currency = row.currency, 
                    status = row.status
                });
            }
            return Json(new {data = packagelists }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RetrieveTPs(int id)
        {
            var pList = Packagelist();
            List<PackageList> packagelists = new List<PackageList>();
            foreach (var row in pList)
            {
                packagelists.Add(new PackageList
                {
                    p_id = row.p_id,
                    p_name = row.p_name,
                    p_price = row.p_price,
                    c_id = row.c_id,
                    c_type = row.c_type,
                    bed_id = row.bed_id,
                    bedtype = row.bedtype,
                    status = row.status
                });
            }
            var response = packagelists.Where(x => x.p_id.Equals(id)).ToList();
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewOTDP(int? id)
        {
            ViewBag.PId = id;
            return View();
        }

        public ActionResult DeleteTDs(int id)
        {
            try
            {
                int delTdates = DeleteTDates(id);
                return Json("Departure dates successfuly deleted, "+ delTdates +" row(s) affected!");
            }
            catch(Exception ex)
            {
                return Json("Error: " + ex.Message);
            }
        }

        public ActionResult DeleteInc(int id)
        {
            try

BookingApp/Areas/AdminPanel/Views/ControlPanel/AddBedRooms.cshtml
@model BookingApp.Areas.AdminPanel.Models.Bedtype

@using (Html.BeginForm("AddBedRooms", "ControlPanel", FormMethod.Post, new { @id = "BRFormData"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row p-2">
        <div class="col-12">
            <div class="form-group">
                <div class="input-group">
                    @Html.EditorFor(model => model.bedtype, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Bedroom Type" } })
                </div>
                @Html.ValidationMessageFor(model => model.bedtype, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <button class="btn btn-success pull-right" id="btnSaveBRtype">Save Bedroom Type</button>
                <button class="btn my-font-14 font-red pull-right" type="button" id="btnSaveBRtypeLoading" disabled>
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Processing...
                </button>
            </div>
        </div>
    </div> 
}

BookingApp/Areas/AdminPanel/Views/ControlPanel/AddCategory.cshtml
@model BookingApp.Areas.AdminPanel.Models.Categories

@using (Html.BeginForm("AddCategory", "ControlPanel", FormMethod.Post, new { @id = "CatFormData" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row p-2">
        <div class="col-12">
            <div class="form-group">
                <div class="input-group">
                    @Html.EditorFor(model => model.c_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Category" } })
                </div>
                @Html.ValidationMessageFor(model => model.c_name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <button class="btn btn-success pull-right" id="btnSavecategory">Save Category</button>
                <button class="btn my-font-14 font-red pull-right" type="button" id="btnSaveCatLoading" disabled>
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Processing...
                </button>
            </div>
        </div>
    </div>
}

BookingApp/Areas/AdminPanel/Views/ControlPanel/AddImage.cshtml
<select name="p_name" class="custom-select dd-user my-font-13" id="_packagename"></select>

BookingApp/Areas/AdminPanel/Views/ControlPanel/ChatBot.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mhyle Travel ChatBot</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    @Scripts.Render("~/styles/fontawesome-kit")
    @Styles.Render("~/styles/tempusdominus-4")
    @Styles.Render("~/styles/bootstrap-4")
    <style>
        #chat-sessions p {
            cursor: pointer !important;
        }
        #scroll-sessions {
            overflow-x: scroll;
            max-height: 800px;
        }
        .chat-msgs {
            max-height: 400px;
            overflow-x: scroll;
        }

        .table-scrolled {
            max-height: 400px;
            overflow-x: scroll;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="card mt-2 p-2">
            <div class="row">
                <div class="col-md-3">
                    <div class="well sidebar-nav">
                        <div class="card" id="scroll-sessions">
                            <h4 class="p-2" style="color:gray">Chat Sessions</h4>
                            <div id="chat-sessions" class="p-2">
                            </div>
                        </div>
                    </div>
                    <!--/.well -->
                </div>
                <!--/span-->
                <div id="chat-content" class="col-md-9">
                    <div id="login" class="card p-2" style="width:400px;">
                        <div id="login-alerts"></div>
                        <fieldset>
                            <legend style="color:gray">Setup agent name</legend>
                            <p>
                                <label style="color:gray">Agent Name</label>
                                <input id="login-name" type="text" class="form-control" placeholder="Agent name">
                            </p>
                            <button id="login-btn" type="submit" class="btn btn-success btn-medium">Start accepting chat</button>
                        </fieldset>
                    </div>
                    <div id="agent-chat" class="card p-2">
                        <div id="real-time-visits" style="color:gray">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                    <h4 style="color:gray">Real time visits</h4>
                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 text-right">
                                    <span id="date_time"></span>
                                </div>
                            </div>
                            <div class="table-scrolled card">
                                <table id="current-visits" class="table table-striped table-bordered" style="color:gray">
                                    <thead>
                                        <tr>
                                            <th>Requested on</th>
                                            <th>Page</th>
                                            <th>Referrer</th>
                                            <th>In Chat</th>
                                            <th>Invite</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                        <div id="all-chatbox" class="card p-4 bg-light mt-2">
                            <div id="chatmsgsinternal" class="chat-msgs"></div>
                        </div>
                        <div id="chat-controls" class="row p-2">
                            <div class="col-12">
                                @*<input id="post-msg" type="text" class="form-control" placeholder="Enter your text here. Enter /list for a list of available commands" />
                                    <button id="post-btn" class="btn btn-primary">Send</button>*@
                                <div class="input-group">
                                    <input id="post-msg" type="text" placeholder="Enter your text here. Enter /list for a list of available commands" class="form-control" aria-label="" aria-describedby="basic-addon1">
                                    <div class="input-group-append">
                                        <button id="post-btn" class="btn btn-primary">Send</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
    </div>
    </div>
    <!--/.fluid-container-->


    <div id="modal-cmd" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header text-left">
                    <h3>Available commands</h3>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery-1")
    @Scripts.Render("~/bundles/bootstrap-4")
    @Scripts.Render("~/bundles/timeage")
    @Scripts.Render("~/bundles/signalr")
    <script src="~/signalr/hubs"></script>
    @Scripts.Render("~/bundles/agentchat")
    @Scripts.Render("~/bundles/dateTime")
    <script type="text/javascript">window.onload = date_time('date_time');</script>
    @*@RenderSection("scripts", required: false)*@
</body>
</html>

BookingApp/Areas/AdminPanel/Views/ControlPanel/Slides.cshtml



<div class="content">
    <div class="container-fluid">
        @*<button type="button" class="btn btn-success pull-left pl-2 pr-2" data-toggle="modal" data-target="#IndexCaptions">
            <i class="fas fa-plus-circle fa-lg"></i> Add index captions
        </button>*@
        <button type="button" class="btn btn-success pull-right pl-2 pr-2" data-toggle="modal" data-target="#IndexSlides">
            <i class="fas fa-plus-circle fa-lg"></i> Add index slides
        </button>
        <div class="card p-2">
            <h2 class="p-2">Index slide shows and captions</h2>
            <fieldset class="scheduler-border">
                <legend class="scheduler-border text-dark">Index image slides</legend>
                <div class="row" id="issImgDisplay">
                    @* dynamic ISS display here *@
                </div>
            </fieldset>
            <div class="row" id="captionDisplay">
                <div class="col-12">
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border text-dark">Index content title</legend>
                        <p class="text-left shadow-effect" id="ContentTitle">

                        </p>
                    </fieldset>
                </div>
                <div class='col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6'>
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border text-dark">First slide caption</legend>
                        <p class='text-left shadow-effect p-2' id="fcContent">

                        </p>
                    </fieldset>
                </div>
                <div class='col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6'>
                    <fieldset class="scheduler-border">
                        <legend class="scheduler-border text-dark">Second slide caption</legend>
                        <p class='text-left shadow-effect p-2' id="scContent">

                        </p>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Package Image -->
<div class="modal fade" id="IndexSlides">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fas fa-window-close"></i></button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <h4 class="my-font-18 text-center font-red p-2" style="opacity:0.8">Add Index Slide Show</h4>
                <hr class="my-border mt-0" />
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-8 col-lg-8 col-xl-8">
                        <span class="btn btn-outline-success btn-file">
                            <span class="fileinput-new">Select slide show images</span>
                            <input type="file" id="files" name="files" multiple />
                        </span>
                        <span class="text-danger my-font-13 imgerror"></span>
                    </div>

                    <div class="col-12 overflow-auto">
                        <div class="card shadow-effect p-2" id="slidePreview">
                            <h4 class="my-font-18 text-center font-red p-2 mt-1" style="opacity:0.8">Slide Preview</h4>
                            <hr class="my-border mt-0" />
                            <div class="row overflow-auto" id="multiimg"></div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <button class="btn btn-success" type="submit" id="btnIndexSlide">Save Slides</button>
                        </div>
                    </div>

                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><strong>Close</strong></button>
            </div>

        </div>
    </div>
</div>


<!-- Edit index slides -->
<div class="modal fade" id="ImgIss">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Slide updating</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="row" name="updateImgDiv">
                        <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                            <span id="imgId">

                            </span>
                            <span class="btn btn-outline-success btn-file">
                                <span class="fileinput-new">Select slide show images</span>
                                <input type="file" id="ufiles" name="ufiles" />
                            </span>
                            <span class="text-danger my-font-13 imgerror"></span>
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6" id="imgPreview">

                        </div>
                        <div class="col-12">
                            <button id="updateISS" class="btn btn-success pull-right">Update</button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>


<!-- Add index Captions -->
<div class="modal fade" id="IndexCaptions">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add Captions</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post">
                    <div class="row" name="captionsEntity">
                        <div class="col-12">
                            <div class="form-group">
                                <input type="text" name="fhCap" class="form-control" placeholder="First slide bolded (or header) caption" />
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control" name="fbCap" placeholder="First slide caption" rows="4"></textarea>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input type="text" class="form-control" name="shCap" placeholder="Second slide bolded (or header) caption" />
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control" name="sbCap" placeholder="Second slide caption" rows="4"></textarea>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" name="IndexT" placeholder="Index Title" type="text" />
                            </div>
                        </div>
                        <div class="col-12">
                            <button id="btnSaveCaptions" class="btn btn-success pull-right">Save</button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>